spring:
  datasource:
    url: jdbc:sqlserver://eproject-springboot-jpa.database.windows.net:1433;database=eproject-springboot-jpa;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: eproject-springboot-jpa
    password: Huy2052002
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8086
